In [31]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [32]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [33]:
vec_king.shape

(300,)

In [34]:
vec_king

array([ 1.25976562e-01,  2.97851562e-02,  8.60595703e-03,  1.39648438e-01,
       -2.56347656e-02, -3.61328125e-02,  1.11816406e-01, -1.98242188e-01,
        5.12695312e-02,  3.63281250e-01, -2.42187500e-01, -3.02734375e-01,
       -1.77734375e-01, -2.49023438e-02, -1.67968750e-01, -1.69921875e-01,
        3.46679688e-02,  5.21850586e-03,  4.63867188e-02,  1.28906250e-01,
        1.36718750e-01,  1.12792969e-01,  5.95703125e-02,  1.36718750e-01,
        1.01074219e-01, -1.76757812e-01, -2.51953125e-01,  5.98144531e-02,
        3.41796875e-01, -3.11279297e-02,  1.04492188e-01,  6.17675781e-02,
        1.24511719e-01,  4.00390625e-01, -3.22265625e-01,  8.39843750e-02,
        3.90625000e-02,  5.85937500e-03,  7.03125000e-02,  1.72851562e-01,
        1.38671875e-01, -2.31445312e-01,  2.83203125e-01,  1.42578125e-01,
        3.41796875e-01, -2.39257812e-02, -1.09863281e-01,  3.32031250e-02,
       -5.46875000e-02,  1.53198242e-02, -1.62109375e-01,  1.58203125e-01,
       -2.59765625e-01,  

In [35]:
import pandas as pd
messages = pd.read_csv('SpamClassifier-master/smsspamcollection/SMSSpamCollection', sep='\t', names=['label', 'message'])

In [36]:
messages

label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [37]:
import re
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

In [38]:
corpus = []

for i in range(0, len(messages)):
    review = re.sub('[^a-zA-Z]', ' ', messages['message'][i])
    review = review.lower()
    review = review.split()
    review = [lemmatizer.lemmatize(word) for word in review]
    review = ' '.join(review)
    corpus.append(review)

In [39]:
corpus

['go until jurong point crazy available only in bugis n great world la e buffet cine there got amore wat',
 'ok lar joking wif u oni',
 'free entry in a wkly comp to win fa cup final tkts st may text fa to to receive entry question std txt rate t c s apply over s',
 'u dun say so early hor u c already then say',
 'nah i don t think he go to usf he life around here though',
 'freemsg hey there darling it s been week s now and no word back i d like some fun you up for it still tb ok xxx std chgs to send to rcv',
 'even my brother is not like to speak with me they treat me like aid patent',
 'a per your request melle melle oru minnaminunginte nurungu vettam ha been set a your callertune for all caller press to copy your friend callertune',
 'winner a a valued network customer you have been selected to receivea prize reward to claim call claim code kl valid hour only',
 'had your mobile month or more u r entitled to update to the latest colour mobile with camera for free call the mobile up

In [40]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [41]:
words = []
for sentence in corpus:
    sent_token = sent_tokenize(sentence)
    for word in sent_token:
        words.append(simple_preprocess(word))

In [42]:
words

[['go',
  'until',
  'jurong',
  'point',
  'crazy',
  'available',
  'only',
  'in',
  'bugis',
  'great',
  'world',
  'la',
  'buffet',
  'cine',
  'there',
  'got',
  'amore',
  'wat'],
 ['ok', 'lar', 'joking', 'wif', 'oni'],
 ['free',
  'entry',
  'in',
  'wkly',
  'comp',
  'to',
  'win',
  'fa',
  'cup',
  'final',
  'tkts',
  'st',
  'may',
  'text',
  'fa',
  'to',
  'to',
  'receive',
  'entry',
  'question',
  'std',
  'txt',
  'rate',
  'apply',
  'over'],
 ['dun', 'say', 'so', 'early', 'hor', 'already', 'then', 'say'],
 ['nah',
  'don',
  'think',
  'he',
  'go',
  'to',
  'usf',
  'he',
  'life',
  'around',
  'here',
  'though'],
 ['freemsg',
  'hey',
  'there',
  'darling',
  'it',
  'been',
  'week',
  'now',
  'and',
  'no',
  'word',
  'back',
  'like',
  'some',
  'fun',
  'you',
  'up',
  'for',
  'it',
  'still',
  'tb',
  'ok',
  'xxx',
  'std',
  'chgs',
  'to',
  'send',
  'to',
  'rcv'],
 ['even',
  'my',
  'brother',
  'is',
  'not',
  'like',
  'to',
  'spea

In [43]:
### Train Word2Vec from scratch
model = gensim.models.Word2Vec(words)

In [44]:
### Get all the vocabulary
model.wv.index_to_key

['to',
 'you',
 'the',
 'it',
 'and',
 'in',
 'is',
 'me',
 'my',
 'for',
 'your',
 'call',
 'of',
 'that',
 'have',
 'on',
 'now',
 'are',
 'can',
 'so',
 'but',
 'not',
 'or',
 'we',
 'do',
 'get',
 'at',
 'ur',
 'will',
 'if',
 'be',
 'with',
 'no',
 'just',
 'this',
 'gt',
 'lt',
 'go',
 'how',
 'up',
 'when',
 'ok',
 'day',
 'what',
 'free',
 'from',
 'all',
 'out',
 'know',
 'll',
 'come',
 'like',
 'good',
 'time',
 'am',
 'then',
 'got',
 'wa',
 'there',
 'he',
 'love',
 'text',
 'only',
 'want',
 'send',
 'one',
 'need',
 'txt',
 'today',
 'by',
 'going',
 'don',
 'stop',
 'home',
 'she',
 'about',
 'lor',
 'sorry',
 'see',
 'still',
 'mobile',
 'take',
 'back',
 'da',
 'reply',
 'dont',
 'our',
 'think',
 'tell',
 'week',
 'hi',
 'phone',
 'they',
 'new',
 'please',
 'later',
 'pls',
 'any',
 'her',
 'ha',
 'co',
 'did',
 'been',
 'msg',
 'min',
 'some',
 'an',
 'night',
 'make',
 'dear',
 'who',
 'here',
 'message',
 'say',
 'well',
 'where',
 're',
 'thing',
 'much',
 'oh',

In [45]:
model.corpus_count

5569

In [46]:
model.epochs

5

In [47]:
model.wv.similar_by_word('kid')

[('stuff', 0.9969409108161926),
 ('doe', 0.996920108795166),
 ('down', 0.9968418478965759),
 ('abt', 0.9967979788780212),
 ('best', 0.9967860579490662),
 ('haha', 0.9967786073684692),
 ('even', 0.9967701435089111),
 ('dat', 0.9967595934867859),
 ('again', 0.9966992139816284),
 ('actually', 0.9966986179351807)]

In [48]:
model.wv.similar_by_word('good')

[('my', 0.9988625049591064),
 ('night', 0.9987611174583435),
 ('great', 0.9987346529960632),
 ('all', 0.9986919164657593),
 ('morning', 0.9986841082572937),
 ('happy', 0.9986825585365295),
 ('nice', 0.9986045956611633),
 ('well', 0.9985752105712891),
 ('oh', 0.9985241293907166),
 ('hey', 0.998502254486084)]

In [49]:
model.wv['good']

array([-0.25971484,  0.34519574,  0.15784709,  0.14338453,  0.12184629,
       -0.68091035,  0.25396624,  0.6828613 , -0.3977078 , -0.14376673,
       -0.22997804, -0.5340535 , -0.04392859,  0.17069572,  0.25830746,
       -0.23484462,  0.21275096, -0.41487345, -0.09528196, -0.76746696,
        0.32710445,  0.1965386 ,  0.13647243, -0.31349725, -0.03623531,
       -0.02477255, -0.28104094, -0.2785374 , -0.35933545,  0.04455252,
        0.47578079,  0.02011203,  0.18539731, -0.2577613 , -0.18939704,
        0.546746  ,  0.07263599, -0.16095899, -0.10295629, -0.6958119 ,
        0.18635526, -0.38006786, -0.26431173,  0.05040518,  0.21221076,
        0.03419364, -0.1940043 , -0.07161997,  0.27136216,  0.19949244,
        0.28874993, -0.25612715, -0.10617233,  0.07143312, -0.06826264,
        0.06142851,  0.23754923,  0.02865914, -0.53357387,  0.25592017,
       -0.02724842,  0.2264752 , -0.0044539 , -0.16553093, -0.40909344,
        0.40716797,  0.16935661,  0.34556037, -0.49483943,  0.58

In [50]:
model.wv['good'].shape

(100,)

In [51]:
words[0] ### all the words of 1st sentence has a vector of 100 size
            ### but we want that for each sentence we get a vector of 100 size so for this we can use
            ### AvgWord2Vec

['go',
 'until',
 'jurong',
 'point',
 'crazy',
 'available',
 'only',
 'in',
 'bugis',
 'great',
 'world',
 'la',
 'buffet',
 'cine',
 'there',
 'got',
 'amore',
 'wat']

In [52]:
def avg_word2vec(doc):
    # remove out-of-vocabulary words
    #sent = [word for word in doc if word in model.wv.index_to_key]
    #print(sent)
    
    return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)
                #or [np.zeros(len(model.wv.index_to_key))], axis=0)

In [53]:
!pip install tqdm

In [54]:
from tqdm import tqdm

In [66]:
### Apply Word2Vec on every sentences
import numpy as np
X = []
for i in tqdm(range(len(words))):
    X.append(avg_word2vec(words[i]))

  6%|▌         | 338/5569 [00:00<00:01, 3375.82it/s]c:\Users\adity\Desktop\Udemy ML DL\venv\lib\site-packages\numpy\core\fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
c:\Users\adity\Desktop\Udemy ML DL\venv\lib\site-packages\numpy\core\_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5569/5569 [00:01<00:00, 3181.01it/s]


In [67]:
X

[array([-0.1747221 ,  0.24001132,  0.11663465,  0.09471944,  0.09431969,
        -0.49057725,  0.17372468,  0.47596046, -0.2728672 , -0.11431035,
        -0.17032096, -0.36805648, -0.06024018,  0.1238791 ,  0.1823971 ,
        -0.15672188,  0.12964733, -0.30038774, -0.06519846, -0.5212534 ,
         0.20153953,  0.12702976,  0.07618821, -0.223075  , -0.02735591,
        -0.01853466, -0.2118698 , -0.18901224, -0.25578418,  0.03064353,
         0.31509575,  0.02164355,  0.11373667, -0.1762576 , -0.13967535,
         0.38050333,  0.07205991, -0.12011859, -0.10901775, -0.47790468,
         0.1186301 , -0.2574668 , -0.19094512,  0.02795171,  0.1497093 ,
         0.01335002, -0.12228713, -0.04286088,  0.20805576,  0.14184704,
         0.17652267, -0.18655805, -0.06057647,  0.0637714 , -0.07624687,
         0.04047327,  0.14944893,  0.00712717, -0.37018692,  0.18229468,
        -0.0086562 ,  0.15912776,  0.00297428, -0.11896191, -0.28593627,
         0.28387162,  0.10345249,  0.22487992, -0.3

In [74]:
len(X)

5569

In [81]:
len(X[2])

100

In [70]:
type(X)

list

In [83]:
X[0].reshape(1,-1).shape

(1, 100)

In [98]:
### Independent feature
df_list = []

for i in range(len(X)):
    df_list.append(pd.DataFrame(X[i].reshape(1, -1)))

df = pd.concat(df_list, ignore_index=True)

C:\Users\adity\AppData\Local\Temp\ipykernel_21336\25902572.py:7: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat(df_list, ignore_index=True)


In [99]:
df.shape

(5569, 100)

In [100]:
df

0         1         2         3         4         5         6   \
0    -0.174722  0.240011  0.116635  0.094719  0.094320 -0.490577  0.173725   
1    -0.163577  0.206129  0.098890  0.080416  0.089872 -0.427148  0.137100   
2    -0.186208  0.255616  0.123851  0.115048  0.077250 -0.526921  0.174501   
3    -0.240724  0.322090  0.151877  0.126596  0.130172 -0.662480  0.227730   
4    -0.204019  0.264485  0.134525  0.102547  0.116604 -0.556828  0.189505   
...        ...       ...       ...       ...       ...       ...       ...   
5564 -0.209044  0.297905  0.155217  0.127206  0.102739 -0.591658  0.209768   
5565 -0.212429  0.281224  0.135691  0.119253  0.111135 -0.589523  0.202864   
5566 -0.238778  0.325357  0.152075  0.116859  0.118654 -0.654258  0.233154   
5567 -0.215733  0.288811  0.139782  0.114070  0.110582 -0.596374  0.203761   
5568 -0.235484  0.308224  0.149539  0.122580  0.119741 -0.639732  0.216570   

            7         8         9   ...        90        91        92  \
0     0.475960 -0.272867 -0.114310  ...  0.356773  0.148017  0.044286   
1     0.417458 -0.239378 -0.093253  ...  0.318783  0.121187  0.032320   
2     0.470919 -0.287803 -0.139574  ...  0.351322  0.148518  0.043556   
3     0.648398 -0.372618 -0.146886  ...  0.487638  0.196022  0.055652   
4     0.547056 -0.315089 -0.130213  ...  0.411745  0.164222  0.050980   
...        ...       ...       ...  ...       ...       ...       ...   
5564  0.553011 -0.331166 -0.151764  ...  0.417233  0.177325  0.057575   
5565  0.565447 -0.340746 -0.135766  ...  0.430536  0.180325  0.039314   
5566  0.640377 -0.364975 -0.159263  ...  0.483320  0.206811  0.064034   
5567  0.574787 -0.331051 -0.145721  ...  0.428006  0.179333  0.059544   
5568  0.619552 -0.352995 -0.155823  ...  0.454746  0.188638  0.061600   

            93        94        95        96        97        98        99  
0     0.054349  0.418634  0.184125  0.157014 -0.195569  0.146996  0.007815  
1     0.040563  0.354298  0.157635  0.136589 -0.182214  0.135013  0.002135  
2     0.039676  0.427141  0.169455  0.105874 -0.227907  0.175588  0.023678  
3     0.080051  0.557559  0.256476  0.228640 -0.268773  0.199819  0.002211  
4     0.068836  0.471668  0.215567  0.184654 -0.233180  0.162357 -0.000178  
...        ...       ...       ...       ...       ...       ...       ...  
5564  0.052331  0.500087  0.199433  0.142984 -0.246031  0.187273  0.025554  
5565  0.057918  0.493695  0.212690  0.169223 -0.253512  0.184608  0.012937  
5566  0.085747  0.562744  0.257694  0.225557 -0.254506  0.187729  0.005187  
5567  0.070088  0.505607  0.226283  0.183310 -0.239247  0.172189  0.003795  
5568  0.070163  0.542580  0.245167  0.199663 -0.262542  0.183618  0.004661  

[5569 rows x 100 columns]

In [ ]:
## Output Features
y = messages[list(map(lambda x: len(x)>0 ,corpus))]
y=pd.DataFrame(y)['label']
y

In [102]:
y.shape

(5569,)

array([ True,  True, False, ...,  True,  True,  True])