In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
## Create array using numpy

# Create 1d array
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [6]:
arr2 = arr1.reshape(6, 1)
arr2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
arr3 = arr1.reshape(2, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 2D array

arr4 = np.array([[1, 2, 3, 4, 5]])
arr4.shape

(1, 5)

In [ ]:
# 2D array

arr4 = np.array([[1, 2, 3, 4], [2, 3, 4, 1]])
print(arr4)
print(arr4.shape)

[[1 2 3 4]
 [2 3 4 1]]
(2, 4)


In [14]:
# Array using inbuilt functions

arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [15]:
arr.reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
## Identity matrix

arr = np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr.dtype

dtype('int64')

In [ ]:
# Attribute in numpy

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: ", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Item size (in bytes): ", arr.itemsize)

Array:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Item size (in bytes):  8


In [23]:
## Vectorization
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element wise addition
print("Addition: ", arr1 + arr2)

# Element wise substraction
print("Substraction: ", arr2 - arr1)

# Element wise multiplication
print("Multiplication: ", arr1 * arr2)

# Element wise division
print("Division: ", arr2 / arr1)


Addition:  [11 22 33 44 55]
Substraction:  [ 9 18 27 36 45]
Multiplication:  [ 10  40  90 160 250]
Division:  [10. 10. 10. 10. 10.]


In [24]:
## Universal Function
arr = np.array([1, 4, 9, 16])

# Square root
print(np.sqrt(arr))

# Exponential
print(np.exp(arr))

# Sine
print(np.sin(arr))

# natural log
print(np.log(arr))

[1. 2. 3. 4.]
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06]
[ 0.84147098 -0.7568025   0.41211849 -0.28790332]
[0.         1.38629436 2.19722458 2.77258872]


In [26]:
## array slicing and indexing

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
print(arr[1][2])
print(arr[1][2: ])
print(arr[1:, 2:])
print(arr[0: 2])
print(arr[0: 2, 2:])
print(arr[0: 2, 1: 3])

7
[7 8]
[[ 7  8]
 [11 12]]
[[1 2 3 4]
 [5 6 7 8]]
[[3 4]
 [7 8]]
[[2 3]
 [6 7]]
