In [2]:
!pip install numpy

In [3]:
import numpy as np

In [4]:
## Create array using numpy

# Create 1d array
arr1 = np.array([1, 2, 3, 4, 5, 6])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5 6]
<class 'numpy.ndarray'>
(6,)


In [6]:
arr2 = arr1.reshape(6, 1)
arr2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [7]:
arr3 = arr1.reshape(2, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# 2D array

arr4 = np.array([[1, 2, 3, 4, 5]])
arr4.shape

(1, 5)

In [ ]:
# 2D array

arr4 = np.array([[1, 2, 3, 4], [2, 3, 4, 1]])
print(arr4)
print(arr4.shape)

[[1 2 3 4]
 [2 3 4 1]]
(2, 4)


In [14]:
# Array using inbuilt functions

arr = np.arange(0, 10, 2)
arr

array([0, 2, 4, 6, 8])

In [15]:
arr.reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [17]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:
np.zeros((5, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
## Identity matrix

arr = np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr.dtype

dtype('int64')